set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line

# https://github.com/equalsraf/win32yank
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'win33yank.exe -i'
bind-key p run 'tmux set-buffer -- \"$(win32yank.exe -o)\"; tmux paste-buffer'
